# Generated by Django 3.1.5 on 2021-05-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlusAufgabe',
        ),
    ]
