# Generated by Django 3.1.5 on 2021-06-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('krs', '0002_delete_plusaufgabe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlusTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=2)),
            ],
        ),
    ]
