# Generated by Django 3.1.5 on 2021-06-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0003_plustask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlusTask',
            new_name='PlusTaskModel',
        ),
    ]
