# Generated by Django 3.1.5 on 2021-06-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0004_auto_20210607_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plustaskmodel',
            name='answer',
        ),
    ]
